title: EphysTools Documentation
description: Documentation for the EphysTools project
baseurl: "/ephystools-docs" # the subpath of your site, e.g. /blog
url: "https://danielparthier.github.io" # the base hostname & protocol for your site
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Plugins
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist

# Navigation links
nav_links:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Docs"
    link: "/docs"

search: true

# Social media links
social_links:
  - name: "GitHub"
    url: "https://github.com/danielparthier"
    icon: "fab fa-github"
  - name: "GitHub Group"
    url: "https://github.com/Schmitz-lab"
    icon: "fab fa-github"
  - name: "ORCID"
    url: "https://orcid.org/0000-0001-8775-024X"
    icon: "ai ai-orcid"

aux_links:
  "View on GitHub":
    - "//github.com/danielparthier/EphysTools"
  footer_content: "Copyright &copy; 2024 Daniel Parthier. Distributed under a <a href=\"https://danielparthier.github.io/ephystools-doc/LICENSE.md\">MIT license.</a>"
